### ISSUE TITLE
MyGet Feed

### ISSUE THREAD

**Issue by estiller** [rowanmiller/Demo-EFCore#1]
Hi,
What is the MyGet feed which is required to build the solution?
It currently references versions of packages which are not in the [aspvnext](https://www.myget.org/gallery/aspnetvnext) feed.

For example, the solution references "Microsoft.AspNetCore.Http.Abstractions" version "1.0.0-rc2-20270", however the latest version in the MyGet feed is 20254.

**Comment by StefH** [comment]
:+1:

**Comment by aarondoss** [comment]
I am also having an issue getting this to build.  I am using the following nuget feed: https://www.myget.org/F/aspnetcidev/  

EFCore101 demo is working but the Performance project is not.  The Performance project includes both EF6 and EFCore (in dev branch).  I think the problem is the cross targeting of stable and dev branches.  Several new RC versions of EFCore have been released since this demo went up.

**Comment by rowanmiller** [comment]
Upgraded to latest RC2 packages and added a NuGet.config so you don't have to worry about configuring package feeds.

**Comment by StefH** [comment]
Ok thanks for the RC2 feed.

**Comment by aarondoss** [comment]
I just did a get on this project and nuget package restore can not find the
missing packages.

I am using the efreleasefeed.

I would like to demo this to my co-workers let me know what I need to do to
get this working.

Thanks,
Aaron

**Comment by aarondoss** [comment]
Never mind, the firewall at my work is blocking myget.

Aaron

**Comment by estiller** [comment]
Great. I can confirm that everything is now compiling on my end as well.
Thanks for the update!
